### ISSUE TITLE
  how to create  a tileset with discrete LODs

### ISSUE THREAD

**Issue by guojs** [AnalyticalGraphicsInc/3d-tiles-samples#17]
I want to create a tileset width discrete LODs  like  the sample  'New York City" show on  www.cesiums.org
https://cesiumjs.org/NewYork/index.html 
can you tell me the steps to achive it

**Comment by lilleyse** [comment]
The main approach there is to place larger buildings higher up in the tree so that they appear before the smaller buildings. With additive refinement both the large and small buildings are rendered simultaneously at a close enough zoom level.

In the future the [cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) is a better place for discussion like this, as we try to keep these issues related to feature requests or bugs.
